name: build
on:
  [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]  # Current Java LTS

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Push build artifacts to main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.event.pull_request == null
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            github.repos.createCommit({
              owner: github.repository_owner,
              repo: github.repository,
              message: 'Automated build',
              files: [
                {
                  path: '/',
                  content: 'Automated build'
                }
              ]
            })
