name: build
on:
  [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]  # Current Java LTS

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Push build artifacts to main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git || git remote add origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
          git push origin main --force --follow-tags
          git push origin main:main --follow-tags
